### ISSUE TITLE
[Feat] - Community 리스트 레이아웃

### ISSUE THREAD

**Issue by ryudg** [ReOpenSG/ReOpenSG#2]
https://github.com/ReOpenSG/ReOpenSG/blob/5b68b2a8bad2cf6cee3ef133a86d6f236d0dda83/src/views/Community.jsx#L11-L65

**Comment by kelvin-chihyun** [comment]
![커뮤니티1](https://github.com/ReOpenSG/ReOpenSG/assets/101504272/e94d6782-106c-4060-95a5-2113ca0036ab)
